### ISSUE TITLE
Agenda for subgroup meeting - July 14, 2020

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#101]
The next subgroup meeting is **July 14, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

* Discussion: Criteria/Requirements for Linear memory GCs

**Comment by binji** [comment]
It was suggested that we have a discussion about criteria/requirements for a linear memory GC. Would anyone like to sign up to present on this topic?

**Comment by taralx** [comment]
I would, but if I spend time on wasm things it will be for the corpus. But 👍 to talking about it, even if there's no specific presentation.

**Comment by sabine** [comment]
Linear memory GC in what sense:
(1) better support for languages that bring their own GC to WASM?
or
(2) a GC provided by WASM that is integrated with the linear memory, as opposed to presenting as an abstract heap?

**Comment by taralx** [comment]
Or (3) a GC that provides chunks of linear memory with distinct pointers?

**Comment by aardappel** [comment]
I guess to me the general question should be:

_"if a language insists on managing its data inside linear memory (because it wants to reuse an existing language implementation, existing (GC) runtime, or other deep integration with C/C++ code, or because linear memory affords it more flexibility as to how data is managed to match the language semantics), how could Wasm support such a language to be more efficient, save on runtime code size and/or integrate better with the host?"_

Besides @taralx #94 and my #78, there's is @RossTate's https://github.com/WebAssembly/design/issues/1340 which is strongly related, and I believe @kripken has had several designs in the past on this topic.

I've already taken up past airtime with mine, and I wasn't going to pursue it further unless there was strong interest from others, so I'd prefer if someone else would speak on the topic :)

**Comment by binji** [comment]
Sorry I haven't followed up on this, I've been on vacation. It sounds like there's interest in discussing linear memory GCs, even without a presentation, is that right? If so, I'd still like to have someone frame the conversation.

**Comment by binji** [comment]
Notes here: https://github.com/WebAssembly/meetings/pull/601
