### ISSUE TITLE
Rename HeapType to ???

### ISSUE THREAD

**Issue by carlopi** [WebAssembly/gc#105]
I am very out of my water, trying to go through all the material related to this proposal, one thing that struck me is that heaptype is a bit confusing, both since it seems to imply that all heap-allocated items have to be garbage collected and that it needs to reside in a special "half" of the linear memory.

It's not very relevant, can also be settled later, but I have the feeling that tying the concept of garbage collectible item to the heap is sort of misleading.

**Comment by carlopi** [comment]
Probably it's not very relevant / need to think more about this, for now I think I can close the issue

**Comment by jakobkummerow** [comment]
> it seems to imply that all heap-allocated items have to be garbage collected and that it needs to reside in a special "half" of the linear memory

More accurately: all managed objects reside _outside_ the linear memory, on the managed heap. And yes, all managed objects are managed (=garbage collected), so tying those concepts together is intentional. "HeapType" is shorter than "ManagedHeapType" ;-)
(When languages like C/C++ talk about "heap memory", that translates to Wasm's linear memory, and is not the "heap" that "HeapTypes" are referring to.)
