### ISSUE TITLE
FAQ: Why not nominal typing?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#14]
I think I'm with you for using structural typing: it decreases coupling across modules.  And I'm not a type guru so please forgive my ignorance here; but it would seem to me that for down-casts, it would be easier to determine that A is-a B if there is a single subtyping DAG.  Also nominal types would allow for more data hiding, if that's a thing; if you don't export a type from a WebAssembly module, then you have a unique "seal" that you can use to brand object that are yours, and reject objects that aren't.  Dunno.

It seems to me that this will be a kind of FAQ if this proposal goes through, and I think the spec would be better if it included some words on why it doesn't go with nominal types.

**Comment by rossberg-chromium** [comment]
Implementations would be expected to hash-normalise all structural types, so that down casts shouldn't cost more.

The problem with nominal types is that they are much less modular. You need to chain them through all module dependencies, which can become difficult in places, artificially sequentialises instantiation, and sometimes even leads to circular dependencies.

That said, we have discussed the possibility of adding abstract types. One option would be through an explicit sort of type definition, the other through abstract exports. In both cases, such types would effectively be nominal.

**Comment by tlively** [comment]
Closing this because the question is answered. Unfortunately we don't have a great FAQ section where we could document this. PRs to add such documentation would be welcome.
