### ISSUE TITLE
Agenda for subgroup meeting - December 1, 2020

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#162]
The next subgroup meeting is **December 1, 2020 at 9am PST (6pm CET)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

None yet.

**Comment by RossTate** [comment]
Would it be useful for me to give a presentation on undecidability of various type systems? I'll try to connect to well-known languages when possible. In particular, there are many simple features that we take for granted but which are actually undecidable (or at least for more complicated than one would realize), and it can be useful to be aware of these pitfalls and the existing techniques for hurdling over them.

**Comment by tlively** [comment]
Yes, this sounds useful. How long do you think the presentation would be?

**Comment by RossTate** [comment]
It's the sort of presentation that could easily be structured as a bunch of small lessons. This means I could just present however many lessons fit the available time and leave leftover lessons for some future meeting. So if no other agenda item comes up, I can take the whole hour, but this might be the sort of material that's best absorbed in smaller doses :)

**Comment by tlively** [comment]
That sounds great. Let's see what other agenda items come in and we can fill extra time with those mini-presentations as we see fit.

**Comment by RossTate** [comment]
Given the issue in #160, one thing I could give a presentation on is how to encode graph coloring into type-checking. Although that issue is specifically about multiple bounds and type annotations, the overall pattern is common and easy to fall into, so it'd be useful to have more eyes for catching the pattern. Follow that, it'd also make sense to give a presentation on how other systems address this problem and how those solutions can and cannot be adapted to WebAssembly.

But that combination would take a whole hour. So there are other type-theory presentations I could give in shorter time to leave room for another presentation.

**Comment by tlively** [comment]
Sounds good 👍 If anyone else has pressing topics to discuss, we can fit them in and do a shorter type-theory presentation, but otherwise lets do the full hour presentation.

**Comment by titzer** [comment]
I won't be able to attend, but +1 for providing a list of examples for undecidability.

**Comment by tlively** [comment]
The meeting notes PR has been created: https://github.com/WebAssembly/meetings/pull/681
