### ISSUE TITLE
Agenda for subgroup meeting - December 15

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#165]
The next subgroup meeting is **December 15, 2020 at 9am PST (6pm CET)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

None yet.

**Comment by RossTate** [comment]
Would it be useful to give a presentation on type-checking again, this time actually on (un)decidability? In particular, I think there would be a lot of benefit to having a shared understanding of both why Java subtyping is undecidable in theory and why Java subtyping is decidable in practice. I might also cover why C# subtyping is decidable but most implementations outside the VM are incomplete due to practical considerations.

**Comment by tlively** [comment]
Sounds good, thanks @RossTate! Do you expect those topics to cover the full hour?

**Comment by RossTate** [comment]
I can take up the full hour, but I don't have to if another topic comes up. I'll just how much background/detail/implications I go into.

**Comment by tlively** [comment]
Thank you all! The PR for the notes is here: https://github.com/WebAssembly/meetings/pull/687.
