### ISSUE TITLE
Conflicting descriptions of RTTs in Overview.md and MVP.md

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#167]
I assume the one in MVP.md is the more up-to-date description? If so, it would be good to change Overview.md to link to MVP.md rather than containing its own description of RTTs to avoid staleness. It also might be worth linking to MVP.md rather than Overview.md from the top-level README.md to make it clear that the former is more authoritative.

**Comment by tlively** [comment]
Also, does this paragraph from Overview.md still hold?

"In order to cast down the type of a struct or array, the aggregate itself must be equipped with a suitable RTT. Attaching runtime type information to aggregates happens at allocation time but is optional. If no RTT is attached then their runtime type is treated as if it was anyref and a down cast to a more specific type will fail. Such aggregates can prevent client code from rediscovering their real type, enforcing a form of parametricity. They can also be optimised more aggressively (e.g., via flattening optimisations), since the VM knows that any possible additional fields forgotten via subtyping can never be rediscovered."

Perhaps I missed it, but I didn't see anything in MVP.md that explicitly called out that structs and arrays may or may not have associated RTTs.

**Comment by rossberg** [comment]
Thanks, yes, some of the overview may be out of sync, though I usually try to update it. Please see #168, which clarifies the top-level warning and updates the RTT section of the overview. The stuff in there still is relevant, since it provides the high-level rationale, while MVP.md focusses on semantics.

The ability to omit RTTs was removed from the MVP some time ago, after discussion with the V8 team.

**Comment by rossberg** [comment]
Closed via #168.
