### ISSUE TITLE
Overlap between ref.test and br_on_cast?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#169]
IIUC,
```wat
(br_on_cast $label (A) (B))
```
is equivalent to
```wat
(br_if $label (ref.test (A) (B)))
```
except that the former also passes the cast value along. That seems like a nice shorthand, but as it's not strictly necessary, perhaps it could be left for after the MVP?

**Comment by rossberg** [comment]
But that difference is crucial, because the value is passed under its _refined_ type! You would have to cast it again separately at the destination otherwise (using ref.cast), such that every runtime type check would have to be performed twice.

Moreover, br_on_cast is designed to allow efficient encoding of a type-switch as a direct sequence:
```
(push ref)
(br_on_null $case0)
(br_on_cast $case1 (rtt1))
(br_on_cast $case2 (rtt2))
(br_on_cast $case3 (rtt3))
```
Such code would become much more long-winded with just ref.test.

**Comment by kripken** [comment]
Thanks @rossberg - yes, guaranteeing the cast isn't done twice does sound useful. I was hoping that an optimizing VM could avoid that even with separate instructions, but you know more about that than me. And a guarantee is nice for baseline compilers too.

Still, to me this feels like it does more than one thing, somehow. Thinking on this some more, maybe we could add a more generic `by_on_nondefault` which gets a value of a defaultable type, and if the value is not the default, it branches with that value. That is,
```wat
(br_on_cast $where
  (get a ref) (get an rtt))
```
would be equivalent to
```wat
(br_on_nondefault $where
  (ref.test (get a ref) (get an rtt))
```
This would be slightly larger, but if it's a recurring pattern then gzip/brotli would help. And it does guarantee no repeated casts like `br_on_cast`. The benefit to `br_on_nondefault` is that we could use it for more things than GC casts, as it's a more generic instruction, so it might end up decreasing overall code size. For example:
```wat
(br_on_nondefault $where
  (call $get-a-ref-which-might-be-null))
```
Without `br_on_nondefault` we'd need to write something like
```wat
(br_if $where
  (i32.eqz
    (ref.is_null
      (local.tee $temp
        (call $get-a-ref-which-might-be-null))))
  (local.get $temp))
```
I think it's a common pattern to check if a reference is non-null, and if so, do something with it. Seems like this could save a bunch of code size.

This could also be useful outside of references, as the default value is often special, like 0 for integers:
```wat
(br_on_nondefault $where
  (i32.xor (..) (..))
```
But I'm not sure how common that is.

What do you think?

**Comment by kripken** [comment]
@rossberg 

ping about my above comment.

I would also like to expand the argument. I may be missing something, but I see the new prototype has `ref.is_func, ref.as_func, br_on_func`, and the same for `data` and `i31`. Similar to the above, have you considered this;

* `ref.as_func` returns null instead of trapping.
* `br_on_func` is then not needed if we add `br_on_nondefault` as proposed above.

That is, by adding a single `br_on_nondefault` we can get the `br_on_*` variants, making the proposal simpler.

If we want `ref.as_*` to trap, then one option could be both trapping and nontrapping ones. But we could also keep the number of instructions lower by adding a single instruction `ref.to_non_null` that traps on null and returns a non-nullable type (so one would do `ref.as_*` followed by `ref.as_non_null` to get a trapping conversion).

Maybe reducing the number of instructions is not a huge priority, but I think it matters. Less to think about both for humans and for machines :grinning:

**Comment by rossberg** [comment]
@kripken:
> Thinking on this some more, maybe we could add a more generic br_on_nondefault which gets a value of a defaultable type, and if the value is not the default, it branches with that value.

Sorry, can you elaborate on the semantics of `br_on_nondefault`? From the examples it seems like he only operand is an i32, so what reference it is using? And what default is it referring to?

Not sure how it is related to `br_on_cast` either -- aren't casts unrelated to defaults?

> Similar to the above, have you considered this;
> 
> * `ref.as_func` returns null instead of trapping.

Then the result type would be nullable, which means you'd need to insert an extra `ref.as_nonnull` in the primary use cases. Moreover, compiling that semantics requires more code on platforms where you could otherwise use a signal handler to capture null accesses -- so the trapping version arguably is closer to native code.

> * `br_on_func` is then not needed if we add `br_on_nondefault` as proposed above.
> 
> That is, by adding a single `br_on_nondefault` we can get the `br_on_*` variants, making the proposal simpler.

Deferring an answer until I understand the instruction better. :)

> If we want `ref.as_*` to trap, then one option could be both trapping and nontrapping ones. But we could also keep the number of instructions lower by adding a single instruction `ref.to_non_null` that traps on null and returns a non-nullable type (so one would do `ref.as_*` followed by `ref.as_non_null` to get a trapping conversion).

Ah, `ref.as_nonnull` already exists in the upstream function reftypes proposal.

Having trapping and non-trapping versions might make sense. But right now I'm having trouble imagining a concrete use case for the latter. When would you need it?

The intended use case for the `as_*` instructions is for use sites of a reference (i.e., concrete accesses), where the producer _knows_ that it is a proper ref, but the Wasm type system is too weak to prove that. So the producer can just force-cast it right there. A null would be a bug in the producer's codegen.

The `br_on_*` instructions are meant to serve the other use cases, where the operand may legally be null in the source program, and the producer needs to implement an observable cast or check semantics.

**Comment by kripken** [comment]
Thanks, good to know `ref.as_nonnull` already exists.

My idea was that `br_on_nondefault` receives an operand, and branches if the value of that operand is not the default for the type. For an `i32`, it would branch on `!= 0`, and for a nullable type it would branch on non-null. If the branch is taken, the value is sent, and in the case of a nullable type, it is sent as non-nullable (for `i32` it would still be the same type, and so less useful there).

But thinking on what you have said, perhaps my case here is not as strong as I'd thought. And really I should support my claims with some real-world data. As this is not urgent, I think I'll close this for now, and open a new issue later with more information and a hopefully clearer proposal, if I see that the data justifies it.

Thanks for the feedback!
