### ISSUE TITLE
Type graph for benchmarking equi-recursive types

### ISSUE THREAD

**Issue by askeksa-google** [WebAssembly/gc#209]
Further to our discussion about equi-recursive types in the April 20 subgroup meeting, here's an example of a type graph for a big, realistic Dart program, translated with dart2wasm (with function bodies stubbed out): [barista3-20210427-stubbed.wasm.gz](https://github.com/WebAssembly/gc/files/6383689/barista3-20210427-stubbed.wasm.gz)

The [source Dart program](https://github.com/askeksa-google/barista3) is about 400kLOC and contains 3671 classes, of which 1828 survive tree shaking and make it into the binary. The translation generally produces one Wasm struct definition per Dart class, except that when a class adds no new fields, it reuses the struct of the superclass.

In the end, the binary contains 1230 struct types (1068 classes, 6 closures, 156 closure contexts), 2 array types and 5737 function types. It also contains RTT globals for each of the classes and closures (1834 in total). Binaryen canonicalizes the 1230 structs down to 661.

A no-passes round-trip through Binaryen takes about 12 seconds here, and it looks like almost all of the time is spent reading and building the types. This does seem like a long time for this amount of types, so it could be interesting to investigate whether this is due to the equi-recursive canonicalization.

**Comment by rossberg** [comment]
Thanks @askeksa-google. Do you happen to have a link to a text version of this module? I get a decoding error (invalid reference type) when trying to load this with the reference interpreter.

**Comment by kripken** [comment]
It loads ok in binaryen, so it seems there is a difference between it and the reference interpreter that we should investigate. (Was that the reference interpreter on [prototype 3](https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit)?)

Here is the wat from binaryen with `--name-types`:

[barista3.wat.zip](https://github.com/WebAssembly/gc/files/6386079/barista3.wat.zip)

**Comment by RossTate** [comment]
Thanks, @askeksa-google! One thing I'm surprised by with the numbers above is that there seems to be only one struct type per class, whereas I would expect there to be two: one describing the structure of the object and one describing the structure of the v-table. My knowledge of Dart is very outdated though. Would you be able to give a *very* high-level sense of how gc-memory is laid out in your compiler?

**Comment by askeksa-google** [comment]
@RossTate Dart has prolific multiple inheritance (any class can be used as an interface), which makes v-tables impractical (or at least that's my impression so far, but I might do a v-table experiment at some point).

Instead, dart2wasm implements method dispatch using a global row-displacement dispatch table. The `i32` at the start of every class struct is the class ID, which is added to a selector-specific offset to index into the dispatch table. Thus, the code for a method call looks like this:
```wat
// push receiver
// push arguments
// push receiver
(struct.get $Object 0)
(i32.const selector_offset)
(i32.add)
(call_indirect $dispatch_table signature)
```
You can actually see the dispatch table in the module. It's the table of 25197 entries and the accompanying initialization elements.

Apart from that, the struct layout is pretty straightforward with one field per Dart field (plus some extra bookkeeping for `late` fields). `bool`, `int` and `double` are represented as `i32`, `i64` and `f64` when non-nullable, and as references to box objects when nullable. Closure contexts do not contain class IDs, but may contain a reference to a parent context or a `this` reference.

**Comment by kripken** [comment]
@rossberg Oh good, thanks for the update!

**Comment by RossTate** [comment]
Ah, I didn't realize Dart's type system blurred classes and interfaces. Then yeah, a v-table wouldn't help much. And it sounds like you're using interface-method tables rather than interface tables, which means you don't need a structure for each interface type then. I can offer some suggestions for optimizing that implementation strategy, but it doesn't affect the gc types, so I won't go on that tangent here.

**Comment by rossberg** [comment]
Hm, after running this through my own experimental minimizer, the Binaryen result with 661 structs looks a bit suspicious. Here is what I get:
```
total 6970 types (5738 funcs, 1230 structs, 2 arrays, 6961 recursion groups, largest 4)
minimized 5566 types (4812 funcs, 753 structs, 1 arrays)
```
I cross-checked that this result is correct by stuffing all input types into a dumb hash set using the naive type equivalence algorithm from the reference interpreter for key equality.

**Comment by kripken** [comment]
What type of minimization does your tool do @rossberg  - does it minify in the type section, or also based on usage in the rest of the wasm?

Binaryen only emits types used somewhere in the module, so that's a possible difference (that is, before we write we collect the used types in the entire program, then sort them by frequency, then emit those). And in this program the bodies are all stubbed out, including that all locals aside from parameters appear to be removed. Some types seem to have no uses left because of that.

(But maybe we have something wrong - does the 661 file at least validate for you?)

In any case, unless I am missing something this should not affect the question of parsing performance, assuming we all measure on the original unminified wasm from @askeksa-google

**Comment by rossberg** [comment]
@kripken, ah, okay, if you're also doing some tree-shaking on the way then that would of course explain it. I just minimise the type section as is, without looking at anything else.

(I haven't looked at the actual minimised file, merely saw the struct number in the OP above.)

**Comment by tlively** [comment]
I don't remember at what point in the pipeline I measured the numbers I measured and it's also possible that I was using a different version of the program. There could also be other explanations, for example there are some subtleties with the text format seeming to have fewer types than the binary format depending on when you measure because only the explicitly declared types participate in the initial canonicalization in Binaryen.

Now that we have multiple implementations and public test cases, when I get a chance I will collect various statistics again and report them here so we can make sure the implementations agree.

**Comment by RossTate** [comment]
@askeksa-google Because Dart types only guarantee interfaces and not class fields/v-tables, does that mean that most fields/parameters of Dart object/class/interface types are being lowered to a simple generic object type (like just a struct with an `i32` field, such as the frequently referenced `$type$0` type in the wat)?

**Comment by askeksa-google** [comment]
A variable with some Dart type `C` is typed with the struct corresponding to the LUB in the superclass hierarchy of all classes implementing `C`. This will sometimes be the `Object` type, and sometimes it will be more precise.

Similarly, the receiver parameter for a method `m` is typed with the LUB of all classes that have `m` in their interface. If the body of the method uses the receiver in a way that requires a more precise type, a cast to the actual enclosing class of `m` is inserted at the start of the method.

I have created a version of the module that includes some more code in the function bodies, specifically the casting of the receiver and code to create closure contexts and store captured parameters into these: [barista3-20210428-stubbed.wasm.gz](https://github.com/WebAssembly/gc/files/6390957/barista3-20210428-stubbed.wasm.gz)

The struct types are the same as before, but the number after canonicalization by Binaryen is higher (771 instead of 661): [barista3-20210428-stubbed.wat.gz](https://github.com/WebAssembly/gc/files/6390961/barista3-20210428-stubbed.wat.gz)

**Comment by RossTate** [comment]
Ah, so you're employing closed-world reasoning to ensure stronger compile-time guarantees, presumably to get at the least efficient field access (rather than always having to use an interface getter/setter). That means the struct types are at least somewhat interesting from an equi-recursive perspective.

But it is worth pointing out that the lack of v-table and interface tables means that the types in this program are likely *substantially* simpler than they would be for Java/Kotlin/C#/Scala. In particular, they'll be much less recursive because they'll only capture recursion due to fields but not recursion do to methods. For example, the v-table for every (non-final) class will have that class's type as the input type of the "this" pointer for all methods newly introduced by the class. Furthermore, methods like `toString` of `java.lang.Object` returns a `java.lang.String`, making the low-level representation of instances of these types mutually recursive even though their surface-level fields are not mutually recursive. There are many classes/interfaces (and even packages) that are mutually recursive through their methods even if not through their fields.

All this is to say that this example, while very useful, should probably be considered as an easy case. In particular, we shouldn't draw any inferences from frequency of recursion as this compilation strategy happens to erase much of the recursion that other compilation strategies for other languages would rely on.

**Comment by askeksa-google** [comment]
Interestingly, if I process the modules with a [version](https://github.com/WebAssembly/binaryen/commit/f2abcbc8d1659d3e6506b1d4128646b892ebc218) of Binaryen right before the addition of [equi-recursive type canonicalization](https://github.com/WebAssembly/binaryen/commit/6aa04fa17a5bf820c8bc3a7801ede7f57a9138e7), it is very quick (less than half a second including writing the `.wat`), and the number of struct types in the output is the same (661 and 771). As I understand it, this version of Binaryen does type canonicalization for non-recursive types and treats recursive types as nominal.

Does this mean that the example actually has no examples of recursive types that are merged by the canonicalization? Or does Binaryen not merge equivalent types?

**Comment by tlively** [comment]
> Does this mean that the example actually has no examples of recursive types that are merged by the canonicalization?

Yes, that's how I would interpret those results. More specifically, it has no self-referential types that are merged. Non-self-referential types that reach self-referential types and are therefore also infinite would still have been merged.

**Comment by tlively** [comment]
Closing this because we have finished benchmarking type systems and have chosen one for the MVP.
