### ISSUE TITLE
Post-MVP: Flat, multi-element arrays

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#222]
Currently, array declarations have a single element type, which of course can be a nullable or non-nullable reference to another struct, array, or function type. We've discussed extensions to this proposal that will allow _inline_ struct types to be declared as field or array elements. That's tricky because some engines will struggle to implement interior pointers that would result from reading a (reference to) an inline struct. We've discussed various ways to express access paths that must result in a scalar in order to avoid, syntactically, exposed interior pointers.

I'd like to propose that we instead simply make space in the encoding for declaring multiple element types in array type declarations and a static index to select the specific (scalar) in array element accesses. This avoids having interior pointers exposed to the engine, but achieves the dense packing of data that is the main intention of arrays-of-structs.

This doesn't solve all issues for languages with interior pointers, even if they choose to use a pair of array, index, to emulate them, because of subtyping. However, it does offer an immediate expressivity gain which achieves the performance goals of inline structs.

In order to support this, we only need to reserve space in the encoding, e.g. by limiting MVP arrays to exactly one element type and a 0 byte for all element accesses.

**Comment by tlively** [comment]
I like the idea in general, but I wonder how easy it would be for compiler authors to use. Does this fall in a grey area where it is not quite expressive enough to be useful in practice? If we feel strongly that multi-element arrays are an important part of our roadmap, then designing the MVP array encoding to be future-compatible with it sounds good to me. Otherwise, if we're less sure of this now, we can always decide to add a new multi-element array heap type constructor and corresponding new accessor instructions in the future.

**Comment by aardappel** [comment]
Would agree this is super useful to have, even if you can't take the address of elements. Using this functionality is typically done for structs with few fields, so copying the whole struct out is cheap. Often you don't even need to copy the whole struct, e.g. a source language `arr[i].field` can result in a single scalar being loaded from the array.

That said, what is the reason to specify multiple elements instead of just a struct element type with some kind of "inline" annotation? The latter would be more uniform with other uses of that struct, and would make it easier to add operations that copy an entire struct out of an array etc.

**Comment by titzer** [comment]
@aardappel I think there are pros and cons to "inline" structs. For one, it is potentially future-compatible with allowing interior pointers (i.e. taking the address of an element). But on the other hand, if we don't do that, IMO, it's an unnecessary mixing of two concepts (structs and vectors of types). For example, we don't require the use of an "inline" struct declaration for return or parameter types, as they are vectors of types. Also, a vector of types appears in the multi-value `select` instruction. They predate the GC proposal, but I think vectors of types make sense of them.

**Comment by aardappel** [comment]
@titzer I think function signatures and structs are different enough to warrant being unrelated declarations.

In the case of your proposed feature however, they are identical. As I said, if we wanted to have an instruction that `memcpy`-ed a struct out of a vector into a single struct, we'd now need code to verify that the "multiple vector element types" and a struct are compatible, which sounds clumsy to me. But maybe we don't want such an instruction?

Another use case is copying a struct out of a vector into locals. If we're never going to have the feature of an inline struct type as locals, but only individual scalar locals, then it would be ok for this vector element not be a struct type, since you'd have to check the "multiple vector element types" against "consecutive local types" anyway, if there was a copy operation. Even if we think don't need a struct copy operation and we can rely on engines being smart enough to turn individual scalar copies into optimal code (repeat sequences of `local.get $vector; <compute index>; vector.get; local.set` all compressed into a single x86 instructions?) we might want such functionality for code compression's sake.

`float2` / `float3` / `float4` etc types are super common in games and other domains Wasm is meant to serve well, so getting this right (and working without dynamic allocation) should be pretty important. I'd say their inline nature is more important than any future "address of" functionality, in C++ passing these by value is already faster than const ref passing for current compilers/architectures afaik.

**Comment by RossTate** [comment]
For arrays, I think it's likely worthwhile to have "memory" arrays, by which I mean that the array is just a big block of bytes that can be accessed akin to linear memory (rather than having artificial distinctions between `i8`/`i16`/`i32`/`i64`/`f32`/`f64`/`f128` arrays). This would also address the `float2`/`float3`/`float4` types that @aardappel mentions.

But, more to the point of the post, my thought is that the GC languages that come to mind that allow surface-level arrays of structs are also the ones that allow interior pointers (although C#'s interior pointers are restricted to have limited lifetime, which makes them *much* easier to manage for garbage collection). This would suggest that the inline-struct approach is the right way to go. But maybe I'm failing to think of a language, or maybe you had an application in mind involving runtime-level arrays?

While I'm at it, C#/.NET and (especially) Go also allocating structs on the stack and then passing (interior) pointers to those stack-allocated structs to functions as if they were heap-allocated pointers. C#/.NET uses syntactic means to ensure the lifetimes of those pointers do not exceed that of the stack frame, whereas Go uses lifetime analyses (but the performance of many programs relies on the fact that these analyses are rather effective). This probably isn't an MVP feature, but it has been in .NET for 2 decades now, so it's worth keeping in mind.

**Comment by titzer** [comment]
I feel like we'd want to first restrict the feature to not allow interior pointers to the elements, because it seriously impacts engine design. As such, we'd want to have a restricted form of array access where the program only reads or writes a single scalar (of the multi-scalar element), rather than reading the entire struct into locals, and discarding all but the desired scalar.

This is why I suggested simply reserving a `0` byte in the array declaration and also in accesses. It's an easy, forward-compatible, scalar-oriented solution.

**Comment by titzer** [comment]
> But maybe I'm failing to think of a language, or maybe you had an application in mind involving runtime-level arrays?

I'd definitely use them in Virgil, because it flattens arrays of tuples into mixed-scalar arrays. It doesn't have interior pointers.

**Comment by titzer** [comment]
> C#/.NET uses syntactic means to ensure the lifetimes of those pointers do not exceed that of the stack frame, whereas Go uses lifetime analyses (but the performance of many programs relies on the fact that these analyses are rather effective). 

AFAICT Go only does escape analysis for scalar replacement, i.e. does not pass pointers to objects on the stack.

**Comment by RossTate** [comment]
Thanks for the example. I'm fine with restricting the usage, but I was taking a different approach: still specify it as an inline struct, but access it with an instruction that takes both an array index and a field within that struct. That way, if we were to add interior pointers, we would still use the same layout-specification design.

The Go team presented in the stacks subgroup recently, and the topic came up. It's possible there was a miscommunication, but my recollection from the meeting and from digging into Go implementation is that they do pass pointers to objects on the stack. When I mentioned that such pointers would not be possible in the GC proposal, they expressed concern that it would be a big performance hit.

**Comment by timjs** [comment]
What's the added value of dedicated multi-element arrays and instructions for them, over inline structs and fat pointers (`ref array * idx` pairs) for interior referencing?

**Comment by titzer** [comment]
I think it's a smaller delta over MVP because we can simply reserve a byte in both the array declaration[1] and access instructions, and then lift the restriction to allow an LEB later. Lifting the restriction on the `0` is literally the only change necessary. Whereas allowing an inline struct but restricting the array element + struct element access to be a single operation (e.g. a single instruction) requires both adding that additional instruction, plus the inline annotation, and making an explicit restriction to disallow a naked `array.get` on that special type.

[1] technically, this reserved byte would be a `1` byte for the array declaration and a `0` byte for the instruction.

Also, I think the future compatibility story for interior pointers (to inline struct fields) is missing key implementation feedback before we know that that upgrade path actually works. I'm thinking specifically about whether said inline structs require object headers, can support RTTs, etc. The more general we attempt to make the feature, the more difficult it becomes to implement.

This way sidesteps that whole issue by intentionally not being more general.

**Comment by tlively** [comment]
I'll close this for now to focus open issues on the MVP, but feel free to reopen this if you have more to add to the discussion at any point. I will also reopen this (and other Post-MVP issues) once it's time to consider and discuss post-MVP extensions.
