### ISSUE TITLE
FYI: nominal types prototyped in Binaryen

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#226]
As of https://github.com/WebAssembly/binaryen/pull/3933, Binaryen supports a basic version of nominal typing. This prototype extension is not meant to become standardized, but is rather meant to enable apples-to-apples comparison of the relative performance of nominal and equirecursive systems when parsing and optimizing Wasm modules.

The text format is extended to support an optional ["extends"](https://github.com/WebAssembly/binaryen/blob/e0a8f40f65b178556f6fcbed778923a36dca64e3/test/lit/nominal-good.wast#L7-L11) clause on type definitions to define nominal subtype relationships. The binary format is extended with new [type encodings](https://github.com/WebAssembly/binaryen/blob/e0a8f40f65b178556f6fcbed778923a36dca64e3/src/wasm-binary.h#L386-L388) that expect a U32LEB type index specifying a supertype to immediately follow the type definition.

It would be great if producers that use Binaryen could add options to use these extensions so we can measure the relative performance of Binaryen with the two type systems on real-world modules.

**Comment by tlively** [comment]
cc @askeksa-google. It would be great to test this extension with Dart :)

**Comment by tlively** [comment]
Note that https://github.com/WebAssembly/binaryen/pull/3935 fixes a known issue with parsing and validating text modules. There is also a known issue that I will work on that causes the emitted binaries to be invalid due to issues preserving the nominal types of functions.

**Comment by askeksa-google** [comment]
I implemented an option for emitting nominal types in `dart2wasm` to try out this Binaryen feature. It reduced the time for a wasm-to-wasm non-optimizing pass-through from 0.8s down to 0.5s. So far so good. :+1:

Usually, when generating types, `dart2wasm` re-uses the struct of the superclass whenever a subclass does not add any fields or type parameters. Due to the requirement with nominal types that the super-rtt must represent a supertype, this optimization was not possible to retain. This resulted in more casts in the code (especially of receivers), for a 2% code size increase.

Many of the receiver casts are dead (`dart2wasm` relies on Binaryen's dead code elimination for removing dead receiver casts), so the code size increase after optimization might be somewhat smaller. Binaryen segfaults if I enable optimizations, though.

The module is here: [barista3-20210625-nt.wasm.gz](https://github.com/WebAssembly/gc/files/6718028/barista3-20210625-nt.wasm.gz)

**Comment by tlively** [comment]
Thanks for trying this out, @askeksa-google! Can you share a small example of the code pattern that no longer worked?

**Comment by askeksa-google** [comment]
Say I have two classes like this:
```dart
class A {
  int x = 0;

  int foo() => x;
}

class B extends A {
  int foo() => bar();

  int bar() => 42;
}
```
The receiver parameter is generally typed as the class where the method is introduced (more generally: LUB of all classes containing the method). So the receiver of `foo()` has type `ref A` and the receiver of `bar()` has type `ref B`.

Currently, `A` and `B` are the same struct (since `B` doesn't add any fields), so the body of `B.foo()` can just pass on the receiver when it calls `bar()`. But if `B` is a strict subtype of `A`, the body of `B.foo()` needs to downcast the receiver from `ref A` to `ref B` before passing it to `bar()`.

**Comment by RossTate** [comment]
Ah cool! Both awesome effort and useful insights.

The good news is that it's totally okay (at least from a type-safety perspective) for multiple rtts to correspond to the same static nominal type. So that problematic constraint can be relaxed (at least from a type-safety perspective).

**Comment by conrad-watt** [comment]
@askeksa-google apologies if I'm misunderstanding, but would it be possible to replicate this optimisation in the nominal system by collapsing `A` and `B` into the same nominal Wasm type, so long as their fields are the same? So instead of declaring separate structs `A` and `B` at the Wasm-level, only one `A_B` struct is declared.

You mentioned "the requirement with nominal types that the super-rtt must represent a supertype" causing an issue. Is the point that `dart2wasm` is able to implement its casts purely using `ref.cast`, so collapsing the types in Wasm wouldn't be semantics-preserving for Dart casts? If so, how does this approach for compiling casts interact with Dart's reified generics?

**Comment by askeksa-google** [comment]
Currently, the RTTs are only used for casts, and the Dart-level type checks are implemented via the class ID included in every object. So for the time being, it would work fine to collapse RTTs as you suggest. There are however some situations where a type check based on the RTT could be significantly faster than the class ID based one. Collapsing the RTTs would preclude that optimization in some cases.

**Comment by RossTate** [comment]
I don't think you want to collapse the RTTs, just the (static) nominal types. That is, whenever a subclass has the same structure as its superclass, use the same nominal type, but still allocate a distinct RTT for the subclass using `rtt.fresh_sub`.

So, for your example, the surface-level types `A` and `B` would lower to the same type `ref $A`. But the lowering of `new A()` would use a different RTT (and v-table) than `new B()`, and similarly the lowerings of `instanceof A`/`(A)` and `instanceof B`/`(B)` would use different RTTs (with the latter being a sub-RTT of the former).

Would that address the issue without precluding other existing optimizations you employ?

**Comment by askeksa-google** [comment]
Yes, if the requirement of `rtt.fresh_sub` is that the supertype is either a declared direct supertype *or the same type* as the subtype, then it should be possible to generate the types exactly as before and also keep the door open for piggy-backing optimizations.

What is the purpose of the "extends" clause in the first place? Would there be any issues with having nominal type equivalence together with (shallow) structural subtyping?

**Comment by RossTate** [comment]
The "extends" clause makes subtyping relationships explicitly declared, as opposed to being implicitly inferred as in structural systems. In short, this makes a number of things easier for the engine, but some things harder for some generators.

**Comment by askeksa-google** [comment]
Right, so with the "extends" clause, the engine needs to check for structural subtyping when validating the type definition, and for transitive declared subtyping at all subtype checks. Without it, it needs to check for structural subtyping at all subtyping checks. It is not clear to me why the former is simpler than the latter, or at least sufficiently simpler to warrant a whole new construct in type definitions.

Is there something more profound to it than this?

**Comment by tlively** [comment]
Having the precise subtype relations can make some of Binaryen's optimizations more powerful. Perhaps we could have inferred the subtypes (and we did some work to try to infer them from RTTs), but it was simpler to have them be explicit. The explicit subtyping will also be necessary if we want to experiment with removing RTTs.

**Comment by kripken** [comment]
Yes, removing RTTs is where we can do a lot more static optimization I believe. For example,
```wat
(ref.cast
  (a non-nullable ref of heap type $A)
  (an rtt of heap type $A)
)
```
Binaryen cannot optimize that even though the heap types match and the value cannot be a null :cry:  because e.g. `(rtt.canon $A) != (rtt.sub $A (rtt.canon $A))`, `(rtt.canon $A) != (rtt.sub $A (rtt.canon $parent))` etc. The precise runtime sequence of `rtt.sub` operations matters.

Without an rtt and with a static heap type in the cast, we could optimize away the cast here:
```wat
(ref.cast $A
  (a non-nullable ref of heap type $A)
)
```

**Comment by timjs** [comment]
It's not entirely clear to me why you can't do the same optimisation with RTTs. My understanding is that you can statically know that two RTTs are the same, because they are just a label to the data layout of a type. So when the compiler sees `(rtt.canon $A)` and later on `rtt.sub $A (rtt.canon $A))`, the layout of the underlaying data is the same, and the compiler knows this. What am I missing?

**Comment by jakobkummerow** [comment]
Two RTTs may be describing the same "data layout" of an object, but they are distinguishable. To continue the example:
```
$rttA1 = (rtt.canon $A)
$rttA2 = (rtt.sub $A (rtt.canon $A))
; both RTTs have static type (rtt $A)
; but they are distinguishable:
$obj1 = (struct.new_with_rtt $A $rttA1 ...)
(ref.test $obj1 $rttA2) ; false
(ref.cast $obj1 $rttA2) ; trap
$obj2 = (struct.new_with_rtt $A $rttA2 ...)
(ref.test $obj2 $rttA1) ; true (implicit upcast to supertype)
(ref.cast $obj2 $rttA1) ; works
```
Of course, if RTT creation _and_ object allocation _and_ the test/cast all happen in the same function and without too many if/else conditional shenanigans, then a tool or compiler could still statically analyze and optimize everything. But if, say, `$obj` is passed in as a function parameter (statically typed as `(ref $A)`), and `$rtt` is loaded from a global (statically typed as `(rtt $A)`, then the result of `(ref.test $obj $rtt)` cannot be statically predicted.

**Comment by RossTate** [comment]
I should point out that the functionality @askeksa-google pointed out would reduce code size by 2% is the same functionality that makes the optimization opportunity that @kripken identified unsound. There may be ways to serve both goals&mdash;I just wanted to raise awareness of the conflict currently between them.

**Comment by kripken** [comment]
Some more promising data on static optimization using nominal typing here:

https://github.com/WebAssembly/binaryen/pull/4052#issuecomment-893078019

That uses nominal types in order to find vtable entries that are constant (100% statically, not using RTTs in any way). It works as well as it does because each class essentially has its own vtable type, so if the same nominal type was used everywhere then the optimization would be less useful. But with structural typing it is not possible to statically differentiate things that are structurally identical, which would make it far more difficult.

**Comment by askeksa-google** [comment]
I dug more into the Dart barista3 code size numbers for structural vs. nominal types after optimization with Binaryen, in particular with the new [TrapsNeverHappen](https://github.com/WebAssembly/binaryen/pull/4059) (`-tnh`) mode. This eliminates many of the extra dead casts in the nominal version.

| Module size | Original | `-O3` | `-O3 -tnh` |
| - | -: | -: | -: |
| Structural | 1768068 | 1516497 | 1472582 |
| Nominal | 1803836 | 1535246 | 1470260 |

It gets even more interesting when looking at the individual section sizes. The type section and code section in particular show significant variations.

| Type section | Original | `-O3` | `-O3 -tnh` |
| - | -: | -: | -: |
| Structural | 73785 | 39619 | 39411 |
| Nominal | 94983 | 60968 | 59452 |

| Code section | Original | `-O3` | `-O3 -tnh` |
| - | -: | -: | -: |
| Structural | 1503863 | 1318295 | 1275840 |
| Nominal | 1516735 | 1313100 | 1251694 |

Here, the extra 20k in the type section (due to more types and explicit supertypes) are offset by 24k less code.

So at least with the currently implemented optimizations in Binaryen, it looks like nominal types (as emitted by dart2wasm) provide slightly more optimization opportunities.

I am curious about what the numbers look like without RTTs. Do we have proposed binary encodings for allocations and casts without RTTs for the experiment?

**Comment by tlively** [comment]
Since this issue was opened we have settled on the isorecursive type system, have experimented with rtt-less instructions, and have implemented many optimizations in Binaryen that take advantage of nominal typing, so this discussion is no longer current.
