### ISSUE TITLE
Agenda for subgroup meeting - September 7

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#237]
The next subgroup meeting will be on **September 7, 2021 at 9-10am PDT (6-7pm CEST)**. Note that this is the day after Labor Day in the US. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda.

So far we have @littledan and @takikawa presenting on requirements and the design space for the JS API.

**Comment by RossTate** [comment]
I would find it helpful if we were to have a discussion of what we're looking for (if anything) with respect to separate compilation for the MVP (as opposed to the Post-MVP), similar to the discussion we had on privacy/encapsulation. For example, we have already had discussions concluding that we expect mutually recursive classes to have to be compiled together in the same module, but do we also expect a class to always be compiled in the same module as its superclass? It affects the design/prioritization space, and I have gotten mixed messages on what we want. As another example, @askeksa-google uses a global dispatch table for method dispatch, rather than a v-table or i-table or im-table. That technique has the advantage of using `call_indirect`, which I understand benefits from optimizations not applicable to `call_ref` or the like, but has the disadvantage that it's not compatible with separate compilation. So knowing what is and is not in scope for the MVP regarding separate compilation can have a pretty big impact on the design/implementation space (and the turnaround time), and I would like to know what I should be taking into consideration at present.

**Comment by tlively** [comment]
Thanks @takikawa and @littledan! And thank you also to @RossTate for being willing to push our other agenda item to next time. The notes are here: https://github.com/WebAssembly/meetings/pull/875.
