### ISSUE TITLE
Unclear if structural equivalence works across modules?

### ISSUE THREAD

**Issue by DLehenbauer** [WebAssembly/gc#26]
Does structural equivalence extend to types defined in different modules?

For example, if module A defines a type `$Vec2`, with an exported function that accepts `$Vec2` like this:
```
(struct $Vec2 (field $x f32) (field $y f32))
(export (func $Vec2_negate (param (ref $Vec2))))
```
...can module B define an equivalent struct...
```
(struct $Point2 (field $x f32) (field $y f32))
```
...and then call the `$Vec2_negate` function defined in module A with an instance of `$Point2` defined in module B?

This initially made me think this was possible...
> In order to avoid spurious type incompatibilities at module boundaries, all types are structural.

...but then I noticed the section on [import/export](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#import-and-export) and wondered if imported/exported functions can only reference imported/exported types?

**Comment by rossberg** [comment]
Well, "structural", by definition, means that it does not matter where and how it's defined. :) So yes, it is supposed to extend across modules.

Imports are types whose definition/structure is _statically_ unknown inside the module. But an imported type can still be found to be structurally equivalent to a known local type when performing casts _dynamically_, once the module is linked. (We have also discussed the possibility of adding real runtime-safe type abstraction for security purposes -- see e.g. issue #7 -- but that would be a future extension.)

**Comment by DLehenbauer** [comment]
I see.  So I'm assuming that the motivation for declaring exported types is so that the engine knows in advance which types might escape the module?  (e.g., it would be a validation error for an exported function to reference a local type that is not exported.)

**Comment by rossberg** [comment]
The motivation is modularity: you want to be able to define modules that are agnostic to however some other module's type is defined exactly, e.g. because they only ever pass around references to it. So they can just ex/import it. Always having to pin down all external type definitions would increase coupling and version dependencies unnecessarily -- and isn't even possible for host types.

You can still reference a local type in an export where it makes sense.

**Comment by DLehenbauer** [comment]
I think there is something that I'm still thinking about the wrong way...  Could you give an example where it would make sense for an export to reference a local type?

**Comment by rossberg** [comment]
Well, since you can't write types inline, any situation where you want to export a function with a non-primitive type but transparent, say, a pair:
```
(type $i32-pair (struct (field i32 i32)))
(func (export "f") (result (ref $i32-pair)) ...)
```
Every client needs to be aware of the definition of the type, so needs to define it itself anyway. Importing it would only allow to use it as an abstract/opaque type ("incomplete" type in C speak).

So: export a type if clients should be able to use it without caring about the structure (like an abstract type), don't export if they need to handle it transparently anyway and therefor hardwire the assumed representation on their end.

**Comment by DLehenbauer** [comment]
I see where I was wrong.  Thanks for the example!
