### ISSUE TITLE
Migrating to iso-recursive types in V8

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/gc#263]
Hi all,
We are planning to migrate from equi- to iso-recursive types in V8. As a basis, we will use the binary format implied by [the iso-recursive interpreter](https://github.com/WebAssembly/gc/blob/iso.interpreter/interpreter/binary/decode.ml), but we might make changes as needed. In any case, we will specify the format in our [specification document](https://bit.ly/3cWcm6Q).

To allow for a transition period, we will maintain support of nominal types, as specified in the specification document. Specifically, we will maintain:

-  `*_subtype` type codes,
- `struct.new`, `struct.new_default`, `array.new`, `array.new_default` and all `*static*` instructions.

Where there is overlap between the iso-recursive format and the nominal format, we will maintain the nominal one, and shift the iso-recursive opcodes as needed.
A module will be allowed to use either nominal or iso-recursive types, but not both. A nominal module will be interpreted as an iso-recursive one where:

- All types have at most one supertype.
- All types are implicitly wrapped in a single recursive group.

All gc-relevant types and instructions which were interpreted as equi-recursive will now switch to iso-recursive.

I have two questions for @rossberg regarding the interpreter's format:

- Why are rtts maintained explicit if only `rtt.canon` is definable?
- If I understand correctly from the binary format, multiple inheritance is supported. Do we have strong incentive for it, since it will complicate the runtime subtyping algorithm?

Please provide any feedback you have for this process, and raise any concerns you might have with dropping equi-recursive types. This post will be edited to reflect your feedback.

**Comment by rossberg** [comment]
Great, looking forward to it!

As for your questions:

> * Why are rtts maintained explicit if only rtt.canon is definable?

Two reasons for explicit RTTs:

1. They provide the ability to customise object creation in host-dependent ways. For example, the JS API can provide ways to define RTTs with a custom prototype for its manifestation in JS. By importing this RTT into Wasm, Wasm code can then produce a respective struct/array with custom JS prototypes. Other embeddings could employ it in similar embedder-specific ways.

2. They provide forward compatibility with [type parameters](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Post-MVP.md#type-parameters), a.k.a. generics. Once functions have type parameters, an RTT created inside such functions is no longer statically fixed. The RTT will generally depend on RTTs representing the type parameters, which ought to be explicit (if we want to avoid the costly and complicated mess of reified generics, which would be a super-bad idea for Wasm).

> * If I understand correctly from the binary format, multiple inheritance is supported. Do we have strong incentive for it, since it will complicate the runtime subtyping algorithm?

Right, I would suggest to exclude them from the GC MVP. However, I'd like to keep the possibility open for a later extension, since single inheritance may not be enough (@titzer has expressed a need for multiple supertypes, for example). So at least the binary format should allow a vector, even if we impose an at-most-one restriction for now (like we did with memories, tables in the MVP).

There are a number of possibilities for reconciling multiple supertypes with efficient casts in a later extension. In the worst case, we could disallow runtime casts on non-linear hierarchies. Preferably, we allow them, but succeed in making them pay as you go, i.e., casts on linear hierarchies remain cheap. Or we introduce more explicit distinctions. TBD.

**Comment by manoskouk** [comment]
This work has been completed for a while now.
