### ISSUE TITLE
Issues to resolve before phase 2?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#265]
I would like to be able to poll for phase 2 in the wider CG soon and this issue is meant to be a meta-discussion about what other discussions we would like to resolve before then.  As a reminder, this is the entry requirement for phase 2:

> Full proposed English spec text available in a forked repo around which a reasonably high level of consensus exists.

Since it is still expected that changes will be made during phase 2, we should block phase 2 only on resolving the most important and cross-cutting issues. Foremost in my mind is getting consensus on the type system, but so far #243 is looking pretty good. What other issues do folks think are important to resolve before phase 2?

**Comment by conrad-watt** [comment]
Since we're currently juggling both a candidate nominal and iso-recursive suite of instructions, I think under normal circumstances, we would only move to phase 2 once we have some idea as to which half should make the final cut (or evidence that both should?).

Personally, while my preference would be to resolve this before phase 2, I would be fine with using phase 2 to signal "we have a reasonably high-level consensus that we're going to pick one of the two current designs", given how long this proposal has been stuck, so long as we're able to keep in mind that this decision is something we'll need to do consensus-building on in future.

So the minimum for me would be a phase 2-style English-languge writeup of both designs that meets the above bar. Is there something being prepared on the nominal side that's analogous to https://github.com/WebAssembly/gc/pull/243?

**Comment by rossberg** [comment]
I agree we should resolve the type system issue before moving to phase 2, but I believe @tlively's post already suggests the same.

Another topic we might want to resolve first is the approach to type annotations (minimal vs maximal). Depending on the outcome, that could introduce a number of changes to the binary format.

**Comment by tlively** [comment]
Yes, I would like to finalize the type system before phase 2. I hope to finish implementing and benchmarking the hybrid isorecursive system in Binaryen over the next couple weeks and if that doesn't produce any surprises, I will be happy to go with #243 over nominal typing.

**Comment by askeksa-google** [comment]
Before we lock down the type system too much, I would like to revisit [i31 as a type dimension](https://github.com/WebAssembly/gc/issues/130). I will post my specific thoughts regarding that on that issue.

**Comment by manoskouk** [comment]
These might not be blockers to move to the next phase, but there are also the questions of `externref` vs. `anyref` (#256), and the idea of introducing a null type.

**Comment by tlively** [comment]
> Before we lock down the type system too much, I would like to revisit i31 as a type dimension. I will post my specific thoughts regarding that on that issue.

I agree that we should continue that discussion, and I'd be happy to continue it into phase 2. More specifically, I would like to have consensus on the system of subtyping and type identity we will use before moving to phase 2, rather than consensus on all the details and options within that system.

**Comment by tlively** [comment]
We decided in our January 25 meeting that getting consensus on type identity and subtyping should be sufficient to move to phase 2, and we decided in our February 8 meeting to poll for phase 2 in the CG meeting on February 15.
