### ISSUE TITLE
I've implemented a Common Lisp with LLVM backend and am interested in generating webassembly

### ISSUE THREAD

**Issue by drmeister** [WebAssembly/gc#28]
I've implemented a Common Lisp that interoperates with C++ and uses LLVM as the backend (github.com/drmeister/clasp).   Currently it supports the Boehm GC and the Memory Pool System GC (MPS; http://www.ravenbrook.com/project/mps/master/manual/html/).

I could generate webassembly with the llvm backend but the lack of GC is a show stopper.

I thought I could provide my own GC (MPS) but the fact that registers aren't stored on the C++ stack is another show stopper.

Let say someone wanted to provide their own GC - is there a way to access the shadow stack of registers?  I realize that the architecture is unknown and the registers are architecture specific and that this may not be reasonable.

**Comment by rossberg** [comment]
There is no built-in "stack of registers". The simple trick for roll-your-own-GC is to maintain your own shadow stack in linear memory, where you spill all local references, so that the GC can find them as roots. Something similar is already done for C/C++, where a shadow stack is generated to store all locals whose address is taken by a program.

**Comment by jfbastien** [comment]
> is there a way to access the shadow stack of registers?

That's a separate (potentially complementary) proposal from GC, which we've discussed on and off on https://github.com/WebAssembly/design but have never explored.

**Comment by drmeister** [comment]
Ok - thanks.  I have a better sense of the challenge involved in bringing "roll-your-own" gc to webassembly.
