### ISSUE TITLE
[interpreter]: crashes on program with globals and invalid rec type use

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/gc#290]
Running the following module in the reference interpreter seems to crash, rather than raise a validation error as I expected:

```
(module
  (rec (type (func)) (type (struct)))
  (rec (type (struct)) (type (func)))
  ;; should have type (ref 0) but initialized with value of type (ref 3)
  (global (ref 0) (ref.func 0))
  (func (type 3)))
```

The result:

```
$ ./wasm /tmp/gc.wat 
./wasm: uncaught exception Wasm.Global.Type
Raised at file "runtime/global.ml", line 11, characters 62-72
Called from file "exec/eval.ml", line 1143, characters 13-68
Called from file "list.ml", line 121, characters 24-34
Called from file "exec/eval.ml", line 1240, characters 14-56
Called from file "script/run.ml", line 507, characters 17-36
Called from file "list.ml", line 110, characters 12-15
Called from file "script/run.ml" (inlined), line 566, characters 2-30
Called from file "script/run.ml", line 571, characters 7-24
Re-raised at file "script/run.ml", line 571, characters 58-67
Called from file "script/run.ml", line 104, characters 4-14
Called from file "script/run.ml", line 140, characters 18-39
Re-raised at file "script/run.ml", line 143, characters 27-36
Called from file "script/run.ml", line 543, characters 16-50
Called from file "list.ml", line 110, characters 12-15
Called from file "script/run.ml", line 104, characters 4-14
Called from file "script/run.ml" (inlined), line 576, characters 24-54
Called from file "main/main.ml", line 43, characters 33-53
Called from file "list.ml", line 110, characters 12-15
Called from file "main/main.ml", line 43, characters 4-72
```

**Comment by takikawa** [comment]
Actually I think I was incorrect that the original example above should fail to validate. It needs a recursive reference like the following to fail to validate:

```
(module
  (rec (type (func (result (ref 0)))) (type (struct)))
  (rec (type (struct)) (type (func (result (ref 1)))))
  (global (ref 0) (ref.func 0))
  (func (type 3) (ref.func 0)))
```

but it should probably still not crash in any case.

**Comment by rossberg** [comment]
Great find! In fact, your initial reaction was correct: the program should not have type-checked, because type 3 is not a subtype of type 0. This was a bug in the validator: it was too loose with the types of functions in the context, which needs to track their exact type indices, not just their expansions, otherwise `ref.func` is typed too loosely.

An analogous bug existed with regard to linking of functions. External function types also need to track the type index under this extension, not just the expanded function type.

See #294 for a fix plus tests. I also added a couple of sentences to the MVP doc to point out the necessary refinements to the handling of function types in the validation context and for external types.
