### ISSUE TITLE
Allow co/contra-variance for nullary `func.bind`?

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#299]
This could be a post-MVP feature, just posting for discussion.

Currently, function types have declared subtyping like structs and arrays, and are limited to a single supertype. There isn't any implicit co-variance or contra-variance in parameter or return types (though those must be checked for a declared subtyping relation). The single-inheritance restriction is intended to make casts fast (i.e. constant time).

However, in the future, we may want richer subtyping for function references. This gets tricky because `call_indirect` does a dynamic signature-match, trapping on failure. Changing that may be hard and/or inefficient.

But I think we could allow `func.bind` to serve the role of a type coercion for function references beyond their declared subtyping relations and still make this work with `call_indirect`'s signature-match semantics.

In particular:

 - Suppose we have `B <: A`
 - Suppose we declare `f1 = B -> A` and `f2 = B -> B`
 - We want to declare `f3 = A -> B`; it is legally a subtype of either, but we can only declare it to be a subtype of one of the above, not both

We could:
 - declare `f3` to be a subtype of `f1`
 - allow `(func.bind f2 (expr: f3))`

In this scenario, `func.bind` would have a more complex validation rule. In particular, for the "residual" type remaining after binding the arguments to the function (the arity difference between `expr` and `f2`, which could be 0), the allows co/contra variance params and returns. When the arity difference is 0, it is basically a type coercion.

For a non-zero arity difference, the assumption is that the engine allocates a *closure*, but for a 0 arity difference, we could as well have the engine generate a *wrapper*. The wrapper function needn't dynamically do anything, its metadata simply has a different signature. Thus when the wrapper is stored into a table, it is stored with the signature of the post-bind.

**Comment by rossberg** [comment]
The typing rule for `func.bind` as written in the Post-MVP doc is:

 - `func.bind $t $t' : [t0* (ref null $t)] -> [(ref $t')]`
    - iff `unroll($t) = [t0* t1*] -> [t2*]`
    - and `unroll($t') = [t1'*] -> [t2'*]`
    - and `t1'* <: t1*`
    - and `t2* <: t2'*`

The rule already has to expand both function types in order to be able to check the arguments and results pointwise. This naturally supports co/contravariance. So `(func.bind $f2 $f3)` will type-check just fine already, no matter if `$f2` and `$f3` are declared subtypes.

And yes, even a nullary func.bind always has to create a wrapper to record the new type, unless `$t` and `$t'` are actually equivalent (which would be a very silly use of the instruction, so probably not worth optimising in an engine).

As an aside, in your example, `f3 <: f2 <: f1`, so you _can_ in fact declare `f3` as a subtype of both transitively (which may still matter in higher-order use cases). For an actual counter example, consider `f1 = A -> A` instead. But `func.bind` would handle that as well.

**Comment by rossberg** [comment]
Closing this as answered.
