### ISSUE TITLE
Expectations for concurrent access to GC types by host and embedded wasm environment

### ISSUE THREAD

**Issue by asb** [WebAssembly/gc#300]
I'm relatively new to the WebAssembly community, and have been working to support the GC proposal in LLVM. Although I've searched the issue tracker it's possible I've missed a previous discussion - apologies if that's the case.

I can see there's discussion imagining multiple Wasm threads accessing and manipulating GC types, but unless there's some extra restriction on the behaviour of the host environment I've missed, this is surely a problem even with a single Wasm thread. Imagine:
* Wasm has access to various struct objects that were passed in from the host environment
* There is only a single thread. A Wasm interpreter executes N instructions, then performs some computation on the host side before returning to the Wasm interpreter.
* During this host-side computation, at least some of the structs exposed to Wasm are modified

Unless I've missed something constraining such behaviour, I think the logical consequence is that any accesses to values within GC types (e.g. accessing a struct field or array element) must be modeled as being `volatile` (in C/C++ terms) to inhibit optimisations that assume the value remains constant (e.g. hoisting such an access out of a loop). Is the above correct?

Also, with no way of coordinating mutation by the host and the embedded Wasm environment, program logic could be broken due to partial updates, right? e.g. `struct { int type_tag; int val1; int val2; };`. Reading this struct from the host side you might read in the middle of an attempt to update all fields - a 'new' `type_tag`, but `val1` and `val2` were not yet updated? There's clearly not anything the compiler can do for this one, it's just something programmers need to be wary of.

**Comment by conrad-watt** [comment]
> Unless I've missed something constraining such behaviour, I think the logical consequence is that any accesses to values within GC types (e.g. accessing a struct field or array element) must be modeled as being `volatile` (in C/C++ terms) to inhibit optimisations that assume the value remains constant (e.g. hoisting such an access out of a loop). Is the above correct?

I think `volatile` is a stronger model than necessary, because IIUC that keyword is used to denote that a value may change at any time even if it appears to never be modified in the source code (e.g. two consecutive reads can't be assumed to take the same value). Calling a host function is more similar to a general situation that presumably also shows up in native compilation - calling an opaque (e.g. dynamically linked) function must be assumed in general to mutate any escaped references.

So when performing optimisations based on dataflow analysis etc, host calls (or more generally any imported/linked function that you can't introspect) must be assumed to read/write any/all possibly-escaped reference values. In contrast to volatile, this means you still have the knowledge that (e.g.) two consecutive reads in straight-line single-threaded code will observe the same value.

It's also worth noting that from LLVM's point of view, at least some host calls will presumably be to known (e.g. WASI) host functions which can maybe be assumed _not_ to arbitrarily modify escaped references. I'm not familiar enough with LLVM's setup to be definite on this.

**Comment by asb** [comment]
> I think `volatile` is a stronger model than necessary, because IIUC that keyword is used to denote that a value may change at any time even if it appears to never be modified in the source code (e.g. two consecutive reads can't be assumed to take the same value). Calling a host function is more similar to a general situation that presumably also shows up in native compilation - calling an opaque (e.g. dynamically linked) function must be assumed in general to mutate any escaped references.

Thanks for such a quick response Conrad. The question of whether the value may change at any time (from the wasm perspective) is really the crux of this issue. If the embedding approach I outlined is considered legal (I could be missing something meaning it isn't), then that kind of pre-emption would be possible, which is why I mentioned the `volatile` approach.
 
> So when performing optimisations based on dataflow analysis etc, host calls (or more generally any imported/linked function that you can't introspect) must be assumed to read/write any/all possibly-escaped reference values. In contrast to volatile, this means you still have the knowledge that (e.g.) two consecutive reads in straight-line single-threaded code will observe the same value.
> 
> It's also worth noting that from LLVM's point of view, at least some host calls will presumably be to known (e.g. WASI) host functions which can maybe be assumed _not_ to arbitrarily modify escaped references. I'm not familiar enough with LLVM's setup to be definite on this.

Though even if we assume mutation of reffed objects on the host side can't be arbitrarily interleaved with wasm execution, the optimisation you suggest may not be possible if calling a host function might be used as a safepoint to trigger some timeslice of host-side computation, potentially including mutation of reffed objects.

In the model you outline above, no host-side mutation is possible other than when the wasm runtime explicitly calls into host functions. That's a reasonable model, but is it required by the current spec?

**Comment by conrad-watt** [comment]
Ah, I think I misunderstood your OP, so apologies for the extraneous parts of my post above! I interpreted the second bullet "...then performs some computation on the host side..." as implying an explicit host call.

> In the model you outline above, no host-side mutation is possible other than when the wasm runtime explicitly calls into host functions. That's a reasonable model, but is it required by the current spec?

Thankfully this is currently mandated by the spec, and it's true in all the embeddings I'm aware of. Someone can chime in here if there's an embedding we want to support that would allow this kind of preemption - it would certainly create some spec headaches!

**Comment by asb** [comment]
> Thankfully this is currently mandated by the spec (at least on a per-thread basis), and it's true in all the embeddings I'm aware of. Someone can chime in here if there's an embedding we want to support that would allow this kind of preemption - it would certainly create some spec headaches!

Fantastic, that does make life easier! Which part of the spec is it that mandates this behaviour?

**Comment by conrad-watt** [comment]
> Fantastic, that does make life easier! Which part of the spec is it that mandates this behaviour?

Now that I'm reading the relevant section of the spec again, perhaps it could be made a little more explicit. The idea is that WebAssembly execution is wholly described in terms of the abstract machine defined [here](https://webassembly.github.io/spec/core/exec/conventions.html). The global state (which includes mutable references) is only allowed to change according to one of the [reduction rules](https://webassembly.github.io/spec/core/exec/instructions.html), of which there are a number describing pure Wasm execution, and a few other cases describing the explicit execution of a [host function](https://webassembly.github.io/spec/core/exec/instructions.html#host-functions). Since there's no "host preemption" or "environment" reduction step defined on top of this, the scenario you brought up woudn't be spec compliant, since the observable behaviour wouldn't correspond to any of the allowed reduction steps.

**Comment by jakobkummerow** [comment]
To add one more point here: I don't think this is a new issue with GC.

Consider a classic linear-memory-based Wasm module compiled from C/C++. The C-to-Wasm compiler (LLVM or otherwise) is certainly allowed to perform the usual C compiler optimizations, such as assuming that a memory location doesn't change over the course of a function if the current function isn't changing it. If Wasm embeddings were allowed to interrupt execution at arbitrary points and interleave it with arbitrary (host-side or whatever) other computations, that would lead to the obvious problems. I don't think the fields of managed structs are any different from locations in linear memory in this regard.

**Comment by asb** [comment]
@jakobkummerow I agree the same questions could be raised about Wasm's linear memory. The reason it didn't come up for me with lienar memory is it's more clearly "owned" by the Wasm side, and there's a clearer analogy to other architectures (where you can rely on memory not changing, other than perhaps some platform-specific address ranges that are volatile).

Thanks both - I'll mark this issue as closed.
