### ISSUE TITLE
Why does the WebAssembly GC need this enriched type system?

### ISSUE THREAD

**Issue by jondgoodwin** [WebAssembly/gc#32]
As a developer of a programming language ([Cone](http://github.com/jondgoodwin/cone)) that plans to target WebAssembly, I was asked to review and provide feedback about the GC proposal.

By way of background, Cone is a memory/race/type safe, static, OO-capable language that intends to offer programmatic support for multiple memory management strategies, including Rust-like static single-owner and lifetime-constrained borrowed references, reference-count, tracing GC and custom allocators (such as pools and arenas). Concurrency safety is ensured using static (Pony-like) or runtime synchronization permissions.

Being able to leverage the browser's GC within a Cone-wasm program would be a blessing. It would significantly reduce the retrieval cost and footprint of any Cone program that required tracing GC references and would presumably allow direct tunnel-through access to browser services, such as WebGL.

I have read through the GC overview several times. It appears to propose a significant enrichment of WebAssembly's type system beyond integers and floats. I am assuming (since it is not stated) that such a type system is a necessary prerequisite to enabling tracing GC support within a wasm module. Why? I am guessing that without such type information, it is believed the GC has no idea how to find the pointers it needs to trace. If I am guessing correctly, it might help others to have this connection stated explicitly.

When I mentally map Cone's type system to the types described in the overview, I came away with several concerns. My first is that in order for Cone to take advantage of the GC, it would require that all of the types in the Overview be implemented (including variant/sum, nested, and others). It would likely also require unrestricted type casts. I suspect anything less would be restrictive and problematic, perhaps fatally so.

And yet, the alternative (that WebAssembly fully embraces this entire, complex type system) concerns me no less. It feels like a significant undertaking that will take a long time to fulfill (years?) and will carry significant technical risks and challenges. Also, Cone uses LLVM for code generation; how much will LLVM IR need to be enriched to correctly pass through the required type information (e.g., mutable/immutable, sum types, and reference variations)? Lastly, I have concerns about performance and type impedance mismatch: I am not clear on exactly how WebAssembly intends to use this type system information, but there could be load or runtime implications of WebAssembly performing a 3rd tier of type checks (Cone and LLVM have already signed off on type correctness), as might be needed to enforce subtyping constraints on casting, etc., not to mention performance hits for ensuring that Cone's type system maps correctly to WebAssembly's.

I do not mean to sound negative or harsh here. I would be delighted to learn my concerns are overblown and unwarranted, if only I knew the full story.

Thinking about this is what led me to the title for this Issue. When I first opened the document, I anticipated reading about a lower-level "API" enabling a wasm program to support the GC. Using this API, a program might:

* allocate a traced object of a specified size, reference tracer function and finalizer
* specify global/stack roots
* invoke read/write barriers

I implemented an incremental, generational GC as part of my earlier language Acorn. I found that using a dispatchable tracing function during the mark phase to identify all the object's pointers offered the promise of type flexibility. This seems even more true for certain types (e.g., sum types or self-typed values) where we do not whether it holds a pointer until runtime.

I realize such a low-level GC API approach is still challenging, but perhaps it might be quicker and less risky than one that requires a full type system. I am not privy to prior history, so it may well be that such an approach has already been evaluated by the team and found wanting,

I have no desire to be disruptive to an orderly unfolding of this proposal. If nothing else, answers to my questions and concerns may help me (and others?) support and facilitate the proposed direction.

**Comment by rossberg** [comment]
Thanks for your feedback! Let me answer your main question. There are three main reasons why we need structure types to describe the layout of allocated memory:

1. GC. As you say, there needs to be some way to explain to the GC where the pointers are in memory. A type description is a simple declarative way of doing so.

2. Safety. The most severe constraint of Wasm is that it absolutely has to be memory-safe. On the Web and similar environments we cannot rely on compilers generating correct code. In fact, code may be malicious. The VM must only assume invariants it can maintain itself. To ensure memory safety, we hence have to ensure that no integer can ever be confused for a reference (they do not point into the guarded linear memory but into arbitrary memory managed by the VM or the host environment). Static type checking is the most efficient way to guarantee that.

3. Interoperability. Wasm essentially is a heterogeneous, multi-language environment. When some code is given a reference it cannot always know where it is coming from and whether it points to one of its own data structures. A language needs to be able to protect itself from malicious code it has to interoperate with. Types provide at least some basic guarantees (and we are discussing a form of type abstraction to enable full encapsulation).

The safety constraint in particular makes for drastically different requirements than conventional low-level languages. In fact, most *safe* low-level languages (such as [typed assembly language](https://en.wikipedia.org/wiki/Typed_assembly_language)) have significantly *more* complex type systems than what is proposed here. We try to keep it simple for the price of potentially requiring more checked casts. We'll have to see what the right balance is in the end, and expect various iterations on the design.

**Comment by aardappel** [comment]
I think language implementors could be given more flexibility if in addition to the types in the current proposal a field could be declared as simply "N bytes of scalar data" (similar to an inline block of linear memory), with load/store ops that are allowed anywhere within the range of N, and interpreted as i/u/f types of various sizes, and either a static or dynamic offset.

An implementor could then choose to forego explicit int/float fields in favor of such a byte field, and do explicit overlapping/unions/alignment/padding/conversion as they desire, at the cost of easy interop for those fields.

Even crazier, one nice feature this could bring is allowing the last element to be a dynamically sized number of scalar bytes (the size implicitly determined by the size of the object), opening up more opportunities for efficient data structures. Though I guess this is only useful if we can guarantee the GC can efficiently know the size of any object dynamically, so that may be unpractical to require of all implementations.

Going yet further, it would be possible to get rid of all types, if each object dynamically can know it consists of N references and M bytes of scalar data, which would be maximally flexible but would likely have a dynamic cost in most implementations (compared to static type sizes), and make interop a lot clumsier (can at best be externally defined).

**Comment by rossberg** [comment]
@aardappel:
> I think language implementors could be given more flexibility if in addition to the types in the current proposal a field could be declared as simply "N bytes of scalar data" (similar to an inline block of linear memory), with load/store ops that are allowed anywhere within the range of N, and interpreted as i/u/f types of various sizes, and either a static or dynamic offset.

With [nesting](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#possible-extension-nesting) this would already be possible, since you can have any array of numeric type in the middle of a struct, and you could cast between them at no cost. In particular, we are thinking that you could freely cast the type of an aggegate to any other that has the same references in the same positions but with completely different sequences of transparent fields in between, as long as they add up to the same length.

> Even crazier, one nice feature this could bring is allowing the last element to be a dynamically sized number of scalar bytes

That is generalised by the idea of [flexible aggregates](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#flexible-aggregates), which isn't restricted to transparent types.

> Going yet further, it would be possible to get rid of all types, if each object dynamically can know it consists of N references and M bytes of scalar data

That would have the big disadvantage that it wouldn't allow you to do arrays of structs in a natural manner -- you would have to transpose such data structures in complicated ways, losing memory locality and efficient copying of entries on the way.

**Comment by jondgoodwin** [comment]
@rossberg  Thank you for your helpful response. Memory safety and protection against harmful actors are clearly important. The type systems in Cone are aimed, in part, to address the memory safety issue. I can appreciate why you would reach for type systems here as well.

Long-term, I can see how this approach guarantees safety while also offering flexible interop. From my perspective, the potential downsides are the concerns I outlined about time-to-deliver, technical risks, and tool chain dependencies (e.g., LLVM). Do you share these concerns?

If time-to-deliver is measured in years, I wonder whether there might be pragmatic waystations on this journey that do not require the full type system to be in place before a language can make use of the browser's GC.

In particular, I would be interested in exploring ways to safely expand the sandbox. As I understand it, the wasm MVP does not guarantee fine-grained memory safety. Instead, the linear memory model isolates the wasm module so that its misuse of memory cannot corrupt other execution units in the browser nor gain access to data not granted to the wasm module. This sandbox approach won't stop a module from shooting itself in the foot, but it offers significant safety protections at a macro level, with  minimal impact to complexity or performance.

Near-term, would it be valuable to explore opening up this sandbox in two ways:

- **Providing native wasm access to web services (e.g., WebGL)**. Would it be possible to ensure reference pointers needed by these APIs are restricted to an indexed location within a GC-managed "table"? If the pointers are opaque, the wasm module cannot corrupt their data, assuming the APIs guarantee their invariants. Clearly, the reference table would need access constraints to ensure its references cannot be corrupted by the wasm module. And obviously, there is a performance impact that arises from indirect access to objects, but these restrictions are a noticeable improvement over having to build and manage a JS shim to obtain wasm access to web services as is required today. A wasm module could potentially take advantage of this without having to fulfill the type system or API requirements to use a GC.

- **Offering programmatic wasm module access to a browser, built-in tracing GC**. Would it be possible to expand the sandbox to include a GC-managed memory block which, like linear memory, is only accessible by the wasm module? If so, a similar sandbox principle would apply: should the wasm module not manage its GC memory safely it would suffer, but no one else would. I believe I could live with such a restriction for some period of time while waiting on the full type system solution. This would be another waypoint that would validate the GC api layer also needed for the full solution.

I hope these suggestions are helpful to the team and WebAssembly's success, which is my aim. If approaches like these have already been explored and rejected as unworkable, I have no interest in resurrecting a dead horse.

Which brings me to my final and most important question: Where do you need help from the Community Group (and PL developers) to help ensure the timely, successful delivery of GC capability to WebAssembly?

**Comment by rossberg** [comment]
@jondgoodwin:
> From my perspective, the potential downsides are the concerns I outlined about time-to-deliver, technical risks, and tool chain dependencies (e.g., LLVM). Do you share these concerns?

Yes, definitely. The current expectation is around something like 1 to 2 years for a "GC MVP" to be available, and that will likely leave out some of the more complex features. But to be honest, the bottleneck with Wasm proposals at the moment is not so much working out design details but building implementations, and that is, to some degree, regardless of their complexity. VM teams are just very busy with a lot of things, and there are lots of proposals.

> Would it be possible to ensure reference pointers needed by these APIs are restricted to an indexed location within a GC-managed "table"?

Indeed, we have discussed this very idea in recent months, and at the last CG meeting decided to carve out the `anyref` type from the GC proposal to handle host references more conveniently. There is no proposal repo yet, but you can see a sketch in [this gist](https://gist.github.com/rossberg/be5962c37e5e749285272622f52b4223). We're shooting for getting levels 0-1 as described there soon.

> Would it be possible to expand the sandbox to include a GC-managed memory block which, like linear memory, is only accessible by the wasm module?

AFAICS, that would require engines to implement a completely new, separate GC, because it couldn't reuse the existing one. Consequently, I don't see how this approach would speed up shipping, rather the opposite. On top of that, the multiple-GCs-in-one-system problem is well-known.

**Comment by jondgoodwin** [comment]
@rossberg 

Appreciate the timing estimate. It helps greatly for planning purposes.

> at the last CG meeting decided to carve out the anyref type from the GC proposal to handle host references more conveniently.

This is great news!

> that would require existing engines to implement a completely new, separate GC

If so, I can understand how that would be problematic. My assumption had been that the existing GC would require adaptations for the type-enriched wasm similar (but not identical) to those for the interim waypoint I suggested. I had hoped that an isolation strategy that reused the existing (but enriched) GC would be possible. I defer to your superior knowledge of the browser GC architecture to determine that this is not so.

> the most important help we will need from language implementers is looking at the proposal, and once there is a prototype, targeting it to evaluate the design in practice

Hopefully, Cone and I will be ready to do exactly that when the time comes. Thank you for your prompt and very helpful responses.

**Comment by PaulBone** [comment]
Hi everyone, I'm a friend of @jondgoodwin and I also work on SpiderMonkey's GC, and I also develop a new language that I hope to one-day target WASM.  In this comment I'm wearing my SpiderMonkey GC hat.

I wanted to expand on @rossberg's comments:

> AFAICS, that would require existing engines to implement a completely new, separate GC,

and

> On top of that, the multiple-GCs-in-one-system problem is well-known.

and @jondgoodwin's comment

> I had hoped that an isolation strategy that reused the existing (but enriched) GC would be possible.

Currently in Firefox JS objects are managed by a mark-sweep collector.  Actually a generational, incremental and zonal mark-sweep-and-sometimes-compact collector.  Meanwhile DOM objects are ref-counted.  However when a dom object points into the JS heap and the JS objects may refer back to DOM objects, it's possible to create cycles that will never be collected.

This is "solved" by introducing another collector called the cycle collector, it ruins periodically and traces both heaps (I don't know the details yet, just that it's there and can be hairy because it requires both heaps to cooperate).  The edge cases WRT cycle collection can give us quiet a bit of grief when we try to change the SpiderMonkey collector. This is the kind of challenge you will face if you introduce a new GC either by having WASM objects use a different GC or have WASM code ship its own GC.

The Servo project has chosen to avoid this problem by just leaveraging the SpiderMonkey GC.  Again, I don't know the details about that, it's just something I've heard.

Meanwhile a lot of GCs actually split themselves up into multiple GCs and it helps to proove them correct and such.  For example a generational GC can be thought of two separate GCs.  Why that's okay is that they use the same tracing code so a lot of code, and design invariants get shared.  So while it can work for multiple heaps in one larger GC. it's not a position you would want to be in as a browser developer.

I hope that helps.  Feel free to correct me if I got anything wrong.

**Comment by titzer** [comment]
One thing to note for "transparent" fields or fields that contain inline raw bytes like linear memories is that linear memory dictates little endian byte order. It was simply too complicated to try to make linear memory bi-endian, endian-neutral, or other solutions. Defining little endian and no automatic alignment for linear memory made sense.

However, for primitive fields in managed objects, I don't think we should allow them to be viewed as raw bytes by default, since that exposes endianness and alignment. If we want little chunks of raw memory inside of objects (a fair use case), there should be an explicit mechanism for declaring that, but it should not be the default.

**Comment by tlively** [comment]
Closing this because the original questions seem to have been answered. Having a custom GC API for integration with linear-memory Wasm has been discussed a lot and might be worth looking into more, but is not the direction chosen by this proposal.
