### ISSUE TITLE
Add formal text for the JS API proposal

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/gc#353]
I just opened a PR with an initial draft of the formal text for the GC proposal's JS API, based on the existing "no-frills" proposal: https://github.com/WebAssembly/gc/pull/352

I wanted to use this issue to explain some of the choices in the proposed spec text and discuss some related issues. The PR modifies `ToWebAssemblyValue` and `ToJSValue` to accommodate GC types. Both assume that the Wasm spec will expose some GC operations to embedders (in the existing appendix: https://webassembly.github.io/spec/core/appendix/embedding.html) such as `i31.new`, `i31.get`, `ref.cast`, and `extern.internalize/externalize`.

GC objects leaving Wasm to go to JS get wrapped in a "GC Exported Object" (similar to "Exported Function"s) which is an exotic JS object with a `[[ObjectAddress]]` slot storing the extern address (i.e., after `extern.externalize` converts the original object), and whose internal methods match the no frills proposal (i.e., the result is generally undefined or some exception is thrown).

When the object comes back to Wasm, the externref is taken out of the slot and goes through `extern.internalize` plus a cast.

I'd appreciate any feedback on the spec text so far, and also have some discussion items that came up while writing this:

  * A [previous discussion](https://github.com/WebAssembly/gc/issues/76) concluded that JS numbers that are in i31ref range should get converted to an i31ref to avoid exposing implementation details. This is a bit weird to spec though because `extern.internalize` is a Wasm spec operation, and it's not obvious if the JS API can constrain it.
    - Note: in the current PR, `ToWebAssemblyValue` with an I31 type will coerce to I32 and then `i31.new` from the result. This itself seems fine, but maybe a bit odd that if you do `ToWebAssemblyValue` to an anyref it's not clear if that can be casted down to an i31ref or not without the constraint described above.
  * Some internal methods like `[[DefineOwnProperty]]` in the no frills proposal are proposed to throw an exception, but it may be better to just return `false` as operations that depend on them check for false and throw a type error anyway (e.g., [CreateDataPropertyOrThrow](https://tc39.es/ecma262/#sec-createdatapropertyorthrow)). The same might apply to `[[PreventExtensions]]` and `[[SetPrototypeOf]]`.

**Comment by rossberg** [comment]
I added a comment regarding internalize to #352. I think i31 should not require special handling in the To{Wasm/JS}Value functions, but that case has to be encapsulated in the semantics of ex/internalize itself.

**Comment by jakobkummerow** [comment]
Regarding i31ref canonicalization:
- I think `extern.internalize` may be the first instruction where it's totally appropriate for the JS API (as well as any other embedding APIs) to define/constrain (parts of) its behavior, because its purpose is specifically to convert embedder values to Wasm values.
- When the type at the boundary is `anyref`, i31 canonicalization must happen too. In this case, coercing to i32 is not the correct behavior: the conversion to i31 must only happen when it is value-preserving, i.e. when an `extern.internalize`+`extern.externalize` roundtrip results in a value that's indistinguishable from the starting value (which is a general invariant we must uphold for all values). I think that means the condition should be "if ((typeof v === "number") && (ToInt32(v) == v) && (v < 2**30) && (v >= -2**30)) { return i31.new(v) } else { return v }".
- The i31 canonicalization that happens explicitly as part of `extern.internalize` is the same as what happens implicitly when the type at the boundary is `anyref`.
- When the type at the boundary is `i31ref`, I'm a little unsure whether it makes more sense to follow the same rules as for `anyref` (i.e. don't coerce non-Number types), or the same rules as for `i32` (i.e. use `ToWebAssemblyValue` to coerce types). I'm leaning towards the former: for all other types T <: anyref, the invariant holds that specifying T at the boundary is equivalent to specifying anyref and then doing `extern.internalize` + `ref.cast T`; I think this equivalence should probably hold for i31ref as well.

Regarding where to throw for `[[DefineOwnProperty]]`: sure, as long as the end result is the same, I don't mind.

Regarding "GC Exported Object": sounds good. It's important that the spec doesn't prevent implementations from simply passing along the pointer, and that repeatedly passing the same Wasm object to JS results in references that are `===`-equal to each other, both of which are accomplished by the "extern value cache". I'm not sure we need `extern_externalize` and "creating a new GC Exported Object" as separate steps: in my mind, creating the Exported Object is what `extern_externalize` does, but I'm not opposed to having them as two steps in the spec if that makes things easier.

**Comment by takikawa** [comment]
Thanks for the feedback, I made some revisions based on the comments here. The biggest change is a new section that details how externalize/internalize should work (with a new `ref.host` value kind for JS values that Wasm doesn't understand).

Other changes:
  * Renamed "GC Exported Object" to "Exported GC Object". The latter seemed clearer.
  * Made [[DefineOwnProperty]], [[PreventExtensions]], and [[SetPrototypeOf]] return false instead of throwing. We can double check to make sure these will cause exceptions to be thrown where needed.
  * i31refs are now converted in the externalize/internalize functions, so it does not matter what type is used at the boundary (i31, any, eq), and it should use the condition described above.

**Comment by takikawa** [comment]
Closing this issue as the JS API spec got merged in #352.
