### ISSUE TITLE
Rename extern.internalize/extern.externalize?

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/gc#432]
In discussions around adding an 'exnref' type (https://github.com/WebAssembly/exception-handling/issues/280), it seemed like there was desire for it to be a new type hierarchy, like any and extern. If this is the case, it could be useful to have instructions to convert from 'exnref' to 'externref' or 'anyref'. This has sort of come up before (https://github.com/WebAssembly/exception-handling/issues/202).

I can't think of a good name for these though, as 'extern.internalize/externalize' seem to have a builtin assumption that you just want to convert between those two hierarchies.

What would folks think about renaming to: `any.from_extern` and `extern.from_any`? This would allow a natural `any.from_exn` or `extern.from_exn`?

**Comment by rossberg** [comment]
Isn't the plan of record not to allow exnrefs to be passed to JavaScript? Then such a conversion wouldn't be very useful.

That said, I don't mind a more extensible naming scheme. Instead of `from` I'd probably use `convert` as a prefix, however, which is more consistent with how we spell numeric conversions.

**Comment by tlively** [comment]
I think the next step is to make a PR implementing this change. @rossberg, would you be up for that?

**Comment by rossberg** [comment]
Sure, though I might not get to it for the next couple of weeks.
