### ISSUE TITLE
`struct` and `array` naming confusion

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/gc#46]
Since types constructed by `struct.new` and `array.new` are both data type **struct**ures, does it make sense to rename `struct` to `record` or something similar?

**Comment by chicoxyzzy** [comment]
(I understand that `record` is named `struct` in C/C++/ Rust but I don't think that this was a good choice in those languages design)

**Comment by rossberg** [comment]
I agree that "struct" is not the best word (it's really just a tuple), but it's so widely established -- and has been since the days of Algol -- that it would not be helpful to use something else. (There are worse misnomers from those days that are still common practice, e.g. confusing the unit type with "void", which is completely off from a semantic perspective.)

I take the liberty to close this issue, unless somebody protests loudly.
