### ISSUE TITLE
Rename GC proposal to "Managed Data Proposal"?

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#5]
GC is so...negative. The garbage is less interesting than the data itself, and GC in particular is just an implementation detail.

**Comment by binji** [comment]
I was thinking about this name too -- it doesn't make it clear whether we're talking about adding ability to use the embedder's GC vs. functionality to implement your own GC.

**Comment by lukewagner** [comment]
To me, "Managed Data" sounds like a marketing term and also like something more general than this specific feature.  FWIW, I like referring to the feature as "GC integration".

**Comment by titzer** [comment]
Ha. First time I have been accused of marketing speech :-)

But I think we need to convey that this is an additional capability of
managed data types, not just manipulating opaque GC references.

**Comment by jfbastien** [comment]
I like that the repo is called GC, and wouldn't change it. We have links to it everywhere. The proposal intro should clarify what is meant by "GC", though. Doesn't really matter that "GC" is negative, it's a fact of the web platform that there is a GC.

**Comment by wingo** [comment]
FWIW when I first saw this spec I thought it would have a smaller scope, just based on the name.  No big opinion here but if it's just a question of links, GitHub is pretty good at forwarding links for renamed repositories, both in checkouts and in web references.

**Comment by lukewagner** [comment]
It's a fair point that the feature contains a lot more than the collection of garbage.

But here's a more concrete argument for my preference above: If we ask ourselves why we need to add this feature to wasm (and not just add sufficient low-level primitives (like stack-inspection) for a compiler to implement GC on top of linear memory), I think the winning argument requires that we assume the host environment *already* has a GC and wasm needs to integrate with it so that wasm apps can: reduce download size and startup time, collect cycles between host GC objects, share GC memory, benefit from host-integrated GC scheduling heuristics, etc.  If the argument was simply: "lots of languages have GC, we should build it into wasm", I think that would be insufficient justification and, just as we said with math functions, it should be in the compiler/toolchain.

So from this perspective, the essential property of this new feature is that it is *integrating* with the host's GC, and so calling it "GC integration" or even "host GC integration" seems appropriate.

**Comment by erights** [comment]
This feature fundamentally changes the character of wasm and sets it on a completely different trajectory. Previously, wasm was a harvard machine model of computation, with a flat address space. Now we have a heap of typed allocated structs pointing at each other with first class #8  opaque unforgeable protected pointers. If we introduce encapsulating closures #7 #10, then we have a lambda / object machine. Then, by "merely" allocating a zero-sized global address space, one may even be able to create an ocap machine, depending on how imports are handled.

I don't love the term "managed". But with this total change in the data model, "<adjective> data" is certainly appropriate, and "managed" is the current term of art. So +1.

**Comment by rossberg-chromium** [comment]
I suspect that the meaning of "managed data" will be less obvious to more
people than "GC". Other than that I don't really care what we call it. In
practice, everybody will probably keep saying "GC" anyway, because it's
shorter and well-known.

**Comment by DLehenbauer** [comment]
Following up on what @erights said above, my sense is that behind the naming discussion, there is a more fundamental decision about whether to treat the GC proposal as a focused host integration feature, or a broader commitment to a first-class type system and runtime.

The later is potentially controversial, because it appears to tilt Web Assembly in favor of managed languages that happen to have compatible type systems.  For example, these languages could benefit from natural interoperability, a fast native allocator, smaller binaries due to reduced runtime payload, and possible 32b/64b neutrality.  Languages that can strictly target the managed runtime might execute w/less overhead, while preserving the same safety guarantees as the full sandbox (#4).

Regardless of what we call the proposal, I personally think that it's far more interesting to treat the type system and runtime as first-class as opposed to an integration feature, and explore how to maximize the benefits for the widest set of languages.

**Comment by rossberg-chromium** [comment]
@DLehenbauer, to clarify, designing in a type system close to any user-facing source language is very much a non-goal. IME, any attempt in that direction is doomed to fail, because of both broad and subtle differences between languages. Thus, the type system in this proposal is intentionally low-level, dealing only with the representation level that producers map to. Moreover, in order to keep complexity at bay, it is fairly limited, and it's instead expected that compilers will have to insert occasional (checked) casts.

**Comment by titzer** [comment]
Phrasing this as an extension might make WebAssembly modular in a sense that it doesn't current have. For example, in some discussions I've used the term "Managed Data Extensions." From this perspective we could view the proposal as an optional component that comes as a self-contained package that extends WASM with new values, types, and operators. A WebAssembly engine that chooses to offer only the current functionality of memories and arithmetic could simply not implement these values, types, or operators, in the same way that a WebAssembly engine running on a very simple embedded processor might not implement SIMD at all.

**Comment by titzer** [comment]
One further thought; supposing that this proposal moves forward and becomes part of WebAssembly, the feature testing story will likely consist of trying to verify a module that contains some managed features. It probably makes sense to group those managed features into a larger granularity extension that can be tested for all at once.

**Comment by erights** [comment]
> ... make WebAssembly modular ... "Managed Data Extensions." ... view the proposal as an optional component that comes as a self-contained package that extends WASM with ...

I like this way of thinking in terms of modularly separable components. But I view this particular issue symmetrically. With wasm-gc, whatever the name, I intend to use it alone, without the unmanaged harvard architecture flat address space, by setting the size of that address space to zero.

I am not suggesting that we need any new mechanism to omit the harvard-arch component of wasm; just that we remember to speak in a way that acknowledges that both sides of this dichotomy are optional. Either can be used to good effect without the other.

**Comment by titzer** [comment]
That's a good point, @erights. We didn't explicitly modularize the linear memory mechanisms, other than separating all the loadmem/storemem opcodes and memory declaration section, but your point stands. It would be a desirable property to allow a credible engine to run "managed only" programs in the future without supporting linear memory at all.

**Comment by lukewagner** [comment]
> It probably makes sense to group those managed features into a larger granularity extension that can be tested for all at once.

Agreed on this subpoint: for features that are intentionally optional (as opposed to "specified, but not yet implemented everywhere") I think it makes sense to formally define this optionality in the spec and then probably some canonical way to test availability (perhaps resurrecting `has_feature`, except now narrowly scoped to only intentionally-optional features).

**Comment by rossberg-chromium** [comment]
Arguably, any of the large feature additions currently under discussion
(threads, SIMD, GC) are worth treating as optional in the same sense.
Conveniently, we already decided to group each under their own instruction
prefixes, so we could say that every such instruction group is a separate
"extension" that can only be omitted as a whole (plus a few non-instruction
bits they also add). Then feature testing just requires trying one
instruction from a group.

**Comment by DLehenbauer** [comment]
I think there may be two different ideas here...

One idea is a formal mechanism for eliding/detecting features that implementors do not feel are appropriate for a particular target environment (e.g., SIMD on embedded).  If wasm is wildly successful, we'll inevitably need this to reach the extreme ends of the device spectrum.  However, this is something I'd recommend we plan for, but postpone implementing, to avoid premature fragmentation.

The other idea is a formal mechanism for denying modules access to capabilities that the administrator, developer, or user feels are inappropriate for the trust level of the module ([#4 again](https://github.com/WebAssembly/gc/issues/4#issuecomment-300845801)).  For example, I'd like to be able to carefully control what memory 3rd party add-ins can read or write.  This is something I don't think we should delay adding to the design, except that we first need to land on a type system.

**Comment by binji** [comment]
Since this conversation hasn't progressed in 3 years, I think we should leave the name as-is. If the subgroup decides to change the scope of this proposal, we can revisit.

As for optional/conditionally-allowed features, we should probably address that more generally, either in the [conditional-sections repo](https://github.com/WebAssembly/conditional-sections), or as a separate design.

Closing.
