### ISSUE TITLE
Type of active element segments

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/gc#538]
According to the [spec](https://webassembly.github.io/gc/core/binary/modules.html#element-section), active element segments without an explicit type have type `(ref null func)` rather than their respective table's type. Is this intended? If so, we don't seem to have a spec test that covers it.

**Comment by manoskouk** [comment]
I am also now noticing that kind 0 and 4 element segments are defined to have type `(ref null func)` over `(ref func)`. Is this intended?

**Comment by rossberg** [comment]
Both properties are intended. The first is to maintain phase separation: in general, the table type is not known during decoding but only during validation, which is too late to use it for parsing disambiguation. The second is for backwards compatibility, because active segments already existed in Wasm 1.0/2.0, i.e., predate non-nullable reference types.

There should be tests for kind 0, since that's the Wasm 1.0 case. Not sure about kind 4, though I thought we have some tests for each case (can't check right now). If not, a PR is of course welcome. :)

**Comment by rossberg** [comment]
Ah, sorry, my mistake, I misremembered. It seems like we indeed refined active segments to be non-nullable (which is conservative). I'll fix the spec,

**Comment by rossberg** [comment]
See WebAssembly/function-references#113

**Comment by manoskouk** [comment]
I think we overcompensated here. I think case 4 should still allow for null references.

**Comment by rossberg** [comment]
Hm, maybe. But that would be an one-off exception from all the other places. Because in fact, I just noticed that there is another place that should have been updated: elemkind should also produce (ref func). That's what the reference interpreter currently does, consistently using (ref func) everywhere.

Either way, I agree that there should be tests. Looking into that just now I realise that the difficulty here is that there actually is no way to directly express some of these cases in the text format, so we'll have to write them in binary.

**Comment by manoskouk** [comment]
But that would not be backwards compatible, at least according to current spec. In current spec, we do not have `(ref func)`, and null references are allowed in element segments.

**Comment by rossberg** [comment]
I suppose you are right. Will fix.

**Comment by rossberg** [comment]
Please see WebAssembly/function-references#114, which also adds tests.
