### ISSUE TITLE
Questions on GC algorithm requirements

### ISSUE THREAD

**Issue by yamt** [WebAssembly/gc#553]
Reading the overview, i couldn't find specific requirements for the GC algorithm
except "Structures are managed -- i.e., garbage-collected -- so manual deallocation is neither required nor possible."

spec-wise,

* is a conservative GC allowed?
* (assuming "large enough" host memory) is a no-op GC, which effectively just leaks memory, allowed?

**Comment by tlively** [comment]
Since the garbage collection algorithm is not observable to the program, the spec doesn't say anything about it and implementations may choose whatever GC implementation they want. A no-op GC is allowed by the spec, but of course as a matter of practicality it will not be a good choice for a very large range of use cases.

**Comment by tlively** [comment]
Closing this as answered, but feel free to reopen if there are follow-on questions.
