### ISSUE TITLE
Potential issue in description?

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/gc#62]
On lines 124 through 141 a simple example of inheritance is given.
However, as I understand it, there is a small error:

Namely, one reason for overriding g() in the D sub class is that the subclass's g has access to D's variables as well as C's variables. Externally there is no difference, but when translated to instance-passing functions one should reflect this.

Accordingly, I believe that the signatures should read:

```
(type $f-sig (func (param (ref $C)) (param i32)))   ;; first param is `this`
(type $g-sig (func (param (ref $C)) (result i32)))
(type $g-D-sig (func (param (ref $D)) (result i32))) ;; a specialization of g's signature
(type $h-sig (func (param (ref $D)) (result i32)))

(type $C (struct (ref $C-vt) (mut i32))
(type $C-vt (struct (ref $f-sig) (ref $g-sig)))    ;; all immutable
(type $D (struct (ref $D-vt) (mut i32) (mut f64))) ;; subtype of $C
(type $D-vt (struct (ref $f-sig) (ref $g-D-sig) (ref $h-sig))) 
```

Of course, I could be barking up the wrong tree too ...

**Comment by rossberg** [comment]
No, that wouldn't type check, since it would be a co-variant refinement of an parameter type, which is unsound in general. To cope with OO's very particular treatment of `this` (which is covariant, but the safety of that can only be guaranteed by global invariants on the compilation scheme, which an engine has no way of verifying) you need to down-cast `this`. See the implementation of ` D.g` shown in the following paragraph.
