### ISSUE TITLE
current frame memory access for js callees

### ISSUE THREAD

**Issue by devsnek** [WebAssembly/gc#67]
It's not possible for JS callees to gain access to S.mems[0] without it being explicitly exported under a prenegotiated name. This means that it's not possible to work with functions that require memory access within the wasm start function, and it makes it impossible to import a function with the esm proposal that can access the memory.

This seems like a super important step to consider with the design of memory moving forward. I've seen it be a design blocker at least once within WASI (https://github.com/WebAssembly/WASI/issues/19), and I've had to work around it in various other projects I've worked on.

Two ideas I have had are being able to pass memories as function arguments, and having a `WebAssembly.currentMemories` getter of some sort.

**Comment by rossberg** [comment]
That seems unrelated to this proposal, which notably does not have any connection to memory objects at all. I suggest creating an issue on the design repo.

(That said, we could provide first-class references to memory objects, the same way we already provide function references. What we cannot do, however, is giving external access to memory that is not exported or otherwise handed out explicitly. We also cannot give access to exports before the start function has terminated, since that would break the initialisation semantics of a module.)
